spring:
  profiles: dev
  data:
    mongodb:
      database: gladtask
      host: localhost
      password:
      port: 27017
      uri: mongodb://localhost/gladtask
jwt:
  secret: gladtask_sk
  expiration: 604800

aws:
  access_key_id: AKIAIZWEZVMYRYZJ2NHA
  secret_access_key: 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

s3:
  bucket: gladtask
  region: us-east-1

server:
    port: ${PORT:8080}

---
spring:
  profiles:  test, default
  data:
    mongodb:
      uri: mongodb+srv://gladtask:gladtask@cluster0-eiykx.mongodb.net/test?retryWrites=true&w=majority


jwt:
  secret: gladtask_sk
  expiration: 604800

aws:
  access_key_id: AKIAIZWEZVMYRYZJ2NHA
  secret_access_key: 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

s3:
  bucket: gladtask
  region: us-east-1

server:
    port: ${PORT:8080}
