spring:
  profiles: dev, default
  data:
    mongodb:
      database: gladtask
      host: localhost
      password:
      port: 27017
      uri: mongodb://35.192.40.49/gladtask
jwt:
  secret: gladtask_sk
  expiration: 604800

aws:
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${SECRET_ACCESS_KEY}

s3:
  bucket: gladtask
  region: us-east-1

server:
    port: ${PORT:8080}

---
spring:
  profiles:  test
  data:
    mongodb:
      uri: ${URI_MONGO}
      database: gladtask
jwt:
  secret: gladtask_sk
  expiration: 604800

aws:
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${SECRET_ACCESS_KEY}

s3:
  bucket: gladtask
  region: us-east-1

server:
    port: ${PORT:8080}
